/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    properties: Property;
    projects: Project;
    amenities: Amenity;
    media: Media;
    'contact-inquiries': ContactInquiry;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-inquiries': ContactInquiriesSelect<false> | ContactInquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  title: string;
  slug: string;
  /**
   * Assigned automatically when the property is created. Permanent and not editable.
   */
  propertyId?: string | null;
  /**
   * Media folder auto-created for this property's permanent Property ID. System-managed — cannot be changed here.
   */
  mediaFolder?: (number | null) | FolderInterface;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  purpose: 'sale' | 'rent' | 'lease';
  propertyCategory?: ('residential' | 'commercial') | null;
  propertyType: 'apartment' | 'house' | 'villa' | 'office' | 'shop' | 'showroom' | 'warehouse' | 'land' | 'other';
  location: {
    locality: string;
    area?: string | null;
    city: string;
    state?: string | null;
    address?: string | null;
    /**
     * Optional. Used later to generate nearby connectivity. Not required to save a property.
     */
    latitude?: number | null;
    /**
     * Optional. Used later to generate nearby connectivity. Not required to save a property.
     */
    longitude?: number | null;
  };
  /**
   * Generate suggestions from the saved property coordinates, then choose which places to add. Only entries with Show on Website enabled are intended for the public listing.
   */
  nearbyConnectivity?: {
    /**
     * Add nearby places manually. Drag to set display order. Hidden entries are kept internally and are not intended for the public website.
     */
    connections?:
      | {
          name: string;
          category:
            | 'transport'
            | 'metro'
            | 'railway-station'
            | 'airport'
            | 'road-highway'
            | 'school'
            | 'college'
            | 'hospital'
            | 'shopping'
            | 'restaurant'
            | 'business-district'
            | 'park'
            | 'religious-place'
            | 'other';
          travelTimeMinutes?: number | null;
          distance?: number | null;
          distanceUnit?: ('km' | 'm') | null;
          displayOnWebsite?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  pricing?: {
    currency?: 'INR' | null;
    price?: number | null;
    priceOnRequest?: boolean | null;
    negotiable?: boolean | null;
    pricePerSqFt?: number | null;
    additionalCharges?: number | null;
    rentAmount?: number | null;
    rentPeriod?: ('monthly' | 'quarterly' | 'yearly') | null;
    securityDeposit?: number | null;
    maintenanceCharges?: number | null;
    maintenanceIncluded?: boolean | null;
    brokerageFee?: number | null;
    totalLeaseAmount?: number | null;
    monthlyLeasePayment?: number | null;
  };
  details?: {
    bedrooms?: number | null;
    bathrooms?: number | null;
    area?: number | null;
    areaUnit?: ('sq-ft' | 'sq-m') | null;
    furnishing?: ('unfurnished' | 'semi-furnished' | 'furnished') | null;
    balconies?: number | null;
    propertyAge?: number | null;
    possessionStatus?: ('ready-to-move' | 'under-construction') | null;
    cabins?: number | null;
    workstations?: number | null;
    meetingRooms?: number | null;
    pantryAvailable?: boolean | null;
    fitOutStatus?: ('bare-shell' | 'warm-shell' | 'fitted') | null;
  };
  buildingDetails?: {
    buildingName?: string | null;
    /**
     * Total number of floors in the building.
     */
    totalFloors?: number | null;
    /**
     * Floor on which this property/unit is located.
     */
    floorNumber?: number | null;
    liftAvailable?: boolean | null;
  };
  amenities?: (number | Amenity)[] | null;
  media?: {
    /**
     * Main property image used as the cover photo in listings and on the property page. Only media filed under this property's own folder can be selected.
     */
    featuredImage?: (number | null) | Media;
    /**
     * Additional property photos. Drag to reorder. Set alt text and optional caption on each Media item. Only media filed under this property's own folder can be selected.
     */
    gallery?: (number | Media)[] | null;
  };
  status: 'draft' | 'available' | 'under-offer' | 'sold' | 'rented';
  tags?:
    | (
        | 'new'
        | 'featured'
        | 'new-development'
        | 'under-construction'
        | 'ready-to-move'
        | 'premium'
        | 'price-reduced'
        | 'commercial'
        | 'residential'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Master amenity library. Properties select from these reusable records; add new amenities here rather than duplicating them on each listing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: number;
  name: string;
  slug: string;
  category?: ('building' | 'lifestyle' | 'convenience') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  slug: string;
  /**
   * Assigned automatically when the project is created (e.g. RER-P-0001). Permanent and not editable. This is RER's own internal reference, not the RERA Registration Number.
   */
  projectId?: string | null;
  /**
   * Media folder auto-created for this project's permanent RER Project Number. System-managed — cannot be changed here.
   */
  mediaFolder?: (number | null) | FolderInterface;
  developer: string;
  /**
   * Draft projects are never shown on the public website or sitemap.
   */
  status: 'draft' | 'upcoming' | 'under-construction' | 'ready-to-move' | 'completed' | 'sold-out';
  /**
   * Tick while this is a current launch. Tagged projects appear under "New Projects" on the homepage and carry a New Launch badge. Untick once the launch is no longer current.
   */
  isNew?: boolean | null;
  /**
   * Optional positioning tags, separate from Project Status. At most two are shown on a project card, and status always takes priority.
   */
  highlightTags?: ('premium' | 'luxury' | 'investment' | 'residential' | 'commercial')[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Short standout points shown as a bullet list, e.g. "Sea-facing towers", "5-minute walk to metro".
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  legal?: {
    /**
     * Supplied by the builder or the RERA authority. Entered manually here (or later by Brochure Convert). Never generated by RER's system — do not confuse with the RER Project Number above.
     */
    reraNumber?: string | null;
    /**
     * Optional. Any additional RERA disclosure text supplied by the builder.
     */
    reraInfo?: string | null;
  };
  location: {
    address?: string | null;
    locality: string;
    area?: string | null;
    city: string;
    state?: string | null;
    pincode?: string | null;
    /**
     * Optional. Used for maps/nearby connectivity.
     */
    latitude?: number | null;
    /**
     * Optional. Used for maps/nearby connectivity.
     */
    longitude?: number | null;
  };
  /**
   * Add nearby places manually. Drag to set display order.
   */
  nearbyConnectivity?: {
    connections?:
      | {
          name: string;
          category:
            | 'transport'
            | 'metro'
            | 'railway-station'
            | 'airport'
            | 'road-highway'
            | 'school'
            | 'college'
            | 'hospital'
            | 'shopping'
            | 'restaurant'
            | 'business-district'
            | 'park'
            | 'religious-place'
            | 'other';
          travelTimeMinutes?: number | null;
          distance?: number | null;
          distanceUnit?: ('km' | 'm') | null;
          displayOnWebsite?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Add one entry per unit configuration (1 BHK, 2 BHK, Penthouse, Commercial unit, etc). Leave pricing/area fields blank where not yet known — they will simply not be shown publicly.
   */
  configurations?:
    | {
        /**
         * e.g. "1 BHK", "3 BHK", "Penthouse", "Retail Shop"
         */
        name: string;
        carpetArea?: number | null;
        minArea?: number | null;
        maxArea?: number | null;
        areaUnit?: ('sq-ft' | 'sq-m') | null;
        startingPrice?: number | null;
        maxPrice?: number | null;
        /**
         * Optional override, e.g. "Price on request" or "Starting from".
         */
        priceLabel?: string | null;
        availability?: ('available' | 'limited' | 'sold-out') | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  projectDetails?: {
    projectType?: ('residential' | 'commercial' | 'mixed-use') | null;
    propertyType?: ('apartment' | 'villa' | 'office' | 'shop' | 'showroom' | 'other') | null;
    possessionStatus?: ('ready-to-move' | 'under-construction') | null;
    /**
     * Optional. Expected or actual possession month/year.
     */
    possessionDate?: string | null;
    /**
     * Free text, e.g. "5th slab completed" — optional detail beyond Possession Status.
     */
    constructionStatus?: string | null;
    numberOfTowers?: number | null;
    numberOfFloors?: number | null;
    totalUnits?: number | null;
    parkingInfo?: string | null;
    developerDescription?: string | null;
  };
  amenities?: (number | Amenity)[] | null;
  /**
   * e.g. "Flooring" / "Vitrified tiles", "Kitchen" / "Modular fittings".
   */
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  media?: {
    /**
     * Hero image used on the project card and the top of the project page. Only media filed under this project's own folder can be selected.
     */
    featuredImage?: (number | null) | Media;
    /**
     * Additional project photos. Drag to reorder. Only media filed under this project's own folder can be selected.
     */
    gallery?: (number | Media)[] | null;
    /**
     * Floor plan images, one per configuration/layout as applicable. Only media filed under this project's own folder can be selected.
     */
    floorPlans?: (number | Media)[] | null;
    /**
     * Overall project layout / master plan image. Only media filed under this project's own folder can be selected.
     */
    masterPlan?: (number | null) | Media;
    /**
     * Optional. A map/location image, if different from the master plan. Only media filed under this project's own folder can be selected.
     */
    locationMapImage?: (number | null) | Media;
  };
  /**
   * Internal tracking for drafts created via Brochure Convert. Never exposed on the public website or API.
   */
  source?: {
    sourceType?: ('pdf' | 'pasted-text' | 'manual') | null;
    sourceFilename?: string | null;
    processedAt?: string | null;
    extractionVersion?: string | null;
    /**
     * Auto-generated notes from Brochure Convert flagging fields that need manual review before publishing.
     */
    extractionNotes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Submissions from the public Contact form. Not publicly readable.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries".
 */
export interface ContactInquiry {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  requirement:
    'buy-property' | 'rent-property' | 'sell-property' | 'new-project' | 'commercial-property' | 'general-enquiry';
  message: string;
  /**
   * The page the enquiry was submitted from.
   */
  source?: string | null;
  /**
   * Internal admin field, not set by the public form.
   */
  status?: ('new' | 'contacted' | 'closed') | null;
  /**
   * Internal admin field, not set by the public form.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'amenities';
        value: number | Amenity;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-inquiries';
        value: number | ContactInquiry;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  propertyId?: T;
  mediaFolder?: T;
  description?: T;
  purpose?: T;
  propertyCategory?: T;
  propertyType?: T;
  location?:
    | T
    | {
        locality?: T;
        area?: T;
        city?: T;
        state?: T;
        address?: T;
        latitude?: T;
        longitude?: T;
      };
  nearbyConnectivity?:
    | T
    | {
        connections?:
          | T
          | {
              name?: T;
              category?: T;
              travelTimeMinutes?: T;
              distance?: T;
              distanceUnit?: T;
              displayOnWebsite?: T;
              id?: T;
            };
      };
  pricing?:
    | T
    | {
        currency?: T;
        price?: T;
        priceOnRequest?: T;
        negotiable?: T;
        pricePerSqFt?: T;
        additionalCharges?: T;
        rentAmount?: T;
        rentPeriod?: T;
        securityDeposit?: T;
        maintenanceCharges?: T;
        maintenanceIncluded?: T;
        brokerageFee?: T;
        totalLeaseAmount?: T;
        monthlyLeasePayment?: T;
      };
  details?:
    | T
    | {
        bedrooms?: T;
        bathrooms?: T;
        area?: T;
        areaUnit?: T;
        furnishing?: T;
        balconies?: T;
        propertyAge?: T;
        possessionStatus?: T;
        cabins?: T;
        workstations?: T;
        meetingRooms?: T;
        pantryAvailable?: T;
        fitOutStatus?: T;
      };
  buildingDetails?:
    | T
    | {
        buildingName?: T;
        totalFloors?: T;
        floorNumber?: T;
        liftAvailable?: T;
      };
  amenities?: T;
  media?:
    | T
    | {
        featuredImage?: T;
        gallery?: T;
      };
  status?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  projectId?: T;
  mediaFolder?: T;
  developer?: T;
  status?: T;
  isNew?: T;
  highlightTags?: T;
  description?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  legal?:
    | T
    | {
        reraNumber?: T;
        reraInfo?: T;
      };
  location?:
    | T
    | {
        address?: T;
        locality?: T;
        area?: T;
        city?: T;
        state?: T;
        pincode?: T;
        latitude?: T;
        longitude?: T;
      };
  nearbyConnectivity?:
    | T
    | {
        connections?:
          | T
          | {
              name?: T;
              category?: T;
              travelTimeMinutes?: T;
              distance?: T;
              distanceUnit?: T;
              displayOnWebsite?: T;
              id?: T;
            };
      };
  configurations?:
    | T
    | {
        name?: T;
        carpetArea?: T;
        minArea?: T;
        maxArea?: T;
        areaUnit?: T;
        startingPrice?: T;
        maxPrice?: T;
        priceLabel?: T;
        availability?: T;
        notes?: T;
        id?: T;
      };
  projectDetails?:
    | T
    | {
        projectType?: T;
        propertyType?: T;
        possessionStatus?: T;
        possessionDate?: T;
        constructionStatus?: T;
        numberOfTowers?: T;
        numberOfFloors?: T;
        totalUnits?: T;
        parkingInfo?: T;
        developerDescription?: T;
      };
  amenities?: T;
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  media?:
    | T
    | {
        featuredImage?: T;
        gallery?: T;
        floorPlans?: T;
        masterPlan?: T;
        locationMapImage?: T;
      };
  source?:
    | T
    | {
        sourceType?: T;
        sourceFilename?: T;
        processedAt?: T;
        extractionVersion?: T;
        extractionNotes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries_select".
 */
export interface ContactInquiriesSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  requirement?: T;
  message?: T;
  source?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}